[package]
name = "webio"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "^0.2.79" 
js-sys = "^0.3.56"
wasm-bindgen-futures = "^0.4.29" 

[dev-dependencies]
futures = "^0.3.21"
wasm-bindgen-test = "^0.3.0"
