[workspace]
members = ["./", "./webio-macros"]

[package]
name = "webio"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "^0.2.79", features = ["serde-serialize"] }
wasm-bindgen-futures = "^0.4.29" 
js-sys = "^0.3.57"
web-sys = { version = "^0.3.57", features = ["Window", "console"] }
webio-macros = { path = "./webio-macros" }
wasm-bindgen-test = "^0.3.0"

[dev-dependencies]
futures = "^0.3.21"
