[package]
name = "webio-macros"
version = "0.1.0-alpha-1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.66"
quote = "^1.0.33"

[dependencies.syn]
version = "^2.0.32"
features = ["derive", "extra-traits", "parsing", "full"]
