[package]
name = "webio-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.36"
quote = "^1.0.17"

[dependencies.syn]
version = "^1.0.90"
features = ["derive", "clone-impls", "extra-traits"]
