name: Webio CI - Check
on: [push, pull_request]

jobs:
  check:
    name: Check Stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check no features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features

      - name: Run cargo check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Run cargo check stream feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=stream

      - name: Run cargo check time feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=time

      - name: Run cargo check macros feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=macros

      - name: Run cargo check event feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=event

      - name: Run cargo check all features for stable
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --features=stream,time,macros.event

    name: Check Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check all features even the ones requiring nightly
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features

  test:
    name: Test Suite On Stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test --all-features

      - name: Run wasm-pack test
        run: wasm-pack test  --all-features --node

    name: Test Suite On Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly 
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test --all-features

      - name: Run wasm-pack test on Node
        run: wasm-pack test  --all-features --node --headless

      - name: Run wasm-pack test on Firefox
        run: wasm-pack test  --all-features --firefox --headless

      - name: Run wasm-pack test on Chrome
        run: wasm-pack test  --all-features --chrome --headless

      - name: Run wasm-pack test on Safari
        run: wasm-pack test  --all-features --safari --headless

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check
