name: Webio CI - Check
on: [push, pull_request]

env:
  STABLE_FEATURES: stream,time,macros,event

jobs:
  check-stable:
    name: Check Stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'


      - name: Run cargo check no features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features

      - name: Run cargo check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Run cargo check stream feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=stream

      - name: Run cargo check time feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=time

      - name: Run cargo check macros feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=macros

      - name: Run cargo check event feature only
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --no-default-features --features=event

      - name: Run cargo check all features for stable
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --features=${{ env.STABLE_FEATURES }}

      - name: Run cargo check for isprime example
        run: >
          cd examples/isprime
          && wasm-pack build --all-features
          && cd www
          && npm install
          && npm build
          && cd ../../..

  check-nightly:
    name: Check Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run cargo check all features even the ones requiring nightly
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features

      - name: Run cargo check for isprime example
        run: >
          cd examples/isprime
          && wasm-pack build --all-features
          && cd www
          && npm install
          && npm build
          && cd ../../..

  test-stable-linux:
    name: Test Suite On Stable (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run cargo test (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Run cargo test (default features)
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo test (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=${{ env.STABLE_FEATURES }}

      - name: Run wasm-pack test on Node (no features)
        run: wasm-pack test --node -- --no-default-features

      - name: Run wasm-pack test on Firefox (no features)
        run: wasm-pack test --firefox --headless -- --no-default-features

      - name: Run wasm-pack test on Chrome (no features)
        run: wasm-pack test --chrome --headless -- --no-default-features

      - name: Run wasm-pack test on Node (default features)
        run: wasm-pack test --node

      - name: Run wasm-pack test on Firefox (default features)
        run: wasm-pack test --firefox --headless

      - name: Run wasm-pack test on Chrome (default features)
        run: wasm-pack test --chrome --headless

      - name: Run wasm-pack test on Node (all features)
        run: wasm-pack test --node -- --features=${{ env.STABLE_FEATURES }}

      - name: Run wasm-pack test on Firefox (all features)
        run: wasm-pack test --firefox --headless -- --features=${{ env.STABLE_FEATURES }}

      - name: Run wasm-pack test on Chrome (all features)
        run: wasm-pack test --chrome --headless -- --features=${{ env.STABLE_FEATURES }}

  test-stable-macos:
    name: Test Suite On Stable (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run wasm-pack test on Safari (no features)
        run: wasm-pack test --safari --headless -- --no-default-features

      - name: Run wasm-pack test on Safari (default features)
        run: wasm-pack test --safari --headless

      - name: Run wasm-pack test on Safari (all features)
        run: wasm-pack test --safari --headless -- --features=${{ env.STABLE_FEATURES }}

  test-nightly:
    name: Test Suite On Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly 
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run cargo test (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Run cargo test (default features)
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo test (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Run wasm-pack test on Node (no features)
        run: wasm-pack test --node -- --no-default-features

      - name: Run wasm-pack test on Firefox (no features)
        run: wasm-pack test --firefox --headless -- --no-default-features

      - name: Run wasm-pack test on Chrome (no features)
        run: wasm-pack test --chrome --headless -- --no-default-features

      - name: Run wasm-pack test on Node (default features)
        run: wasm-pack test --node

      - name: Run wasm-pack test on Firefox (default features)
        run: wasm-pack test --firefox --headless

      - name: Run wasm-pack test on Chrome (default features)
        run: wasm-pack test --chrome --headless

      - name: Run wasm-pack test on Node (all features)
        run: wasm-pack test --node -- --all-features

      - name: Run wasm-pack test on Firefox (all features)
        run: wasm-pack test --firefox --headless -- --all-features

      - name: Run wasm-pack test on Chrome (all features)
        run: wasm-pack test --chrome --headless -- --all-features

  test-nightly-macos:
    name: Test Suite On Nightly (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run wasm-pack test on Safari (no features)
        run: wasm-pack test --safari --headless -- --no-default-features

      - name: Run wasm-pack test on Safari (default features)
        run: wasm-pack test --safari --headless

      - name: Run wasm-pack test on Safari (all features)
        run: wasm-pack test --safari --headless -- --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check
